---
title: "week2Project"
author: "Shuai"
date: "4/21/2017"
output: html_document
---

```{r setup, include = FALSE,warning = F,message = F}
knitr::opts_chunk$set(echo = F)
```

```{r}
library(datasets)
quakes<-quakes
```

```{r}
library(leaflet)
```

```{r}
set.seed(4-21-2017)
mysample <- quakes[sample(1:nrow(quakes), 10,
  	replace=FALSE),]
```
## Interactive Map of Fuji's Earthquake
1. Dataset
  the earthquake dataset from R's {dataset}.

2. Play with it!
  use scroll to see individual points of the cluster. Hover each point to see the earthquake information.
```{r}
quakes %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(label=as.character(quakes$mag), clusterOptions = markerClusterOptions())
```
<!-- chunk comments -->
<!-- Instructions -->

<!-- Create a web page using R Markdown that features a map created with Leaflet. -->

<!-- Host your webpage on either GitHub Pages, RPubs, or NeoCities. -->

<!-- Your webpage must contain the date that you created the document, and it must -->
<!-- contain a map created with Leaflet. We would love to see you show off your -->
<!-- creativity! Review criterialess The rubric contains the following two questions: -->

<!-- Does the web page feature a date and is this date less than two months before -->
<!-- the date that you're grading this assignment? Does the web page feature an -->
<!-- interactive map that appears to have been created with Leaflet? -->